### ISSUE TITLE
Hardcoded customer name in topology connector

### ISSUE THREAD

**Issue by pkoro** [ARGOeu/ARGO#168]
In lines [140-149][l1] in the GOCDB topology connector there are a few hardcoded references to the `EGI` customer (I suppose they refer to the scopes `EGI` and `Local` found on the EGI GOCDB endpoint). Given that we provide the scope we want to fetch in the configuration file (``customer.conf`) maybe it should be set in the code via that configuration file (as long as it is found I suppose). 

[l1]: https://github.com/ARGOeu/argo-egi-connectors/blob/master/bin/topology-gocdb-connector.py#L140-L149

**Comment by vrdel** [comment]
The thing is that I'm actually fetching the whole topology from GOCDB for both scopes that it supports (EGI, Local) in one call and then I apply filters specific for each job. I wanted to avoid multiple calls to feed provider so I'm querying GOCDB only once, not for every job that we have so you can think of those lines as something that actually precedes parsing of any tags (filters) in customer.conf. Basically, parsing of customer.conf is coded in a such way that it firstly finds out all distinct feeds across all jobs, fetch complete topology from each of them and then it applies filters specific for each job.

That being said, I really need to explicitly say which scope I'm fetching, because if I don't, GOCDB will give me only EGI entities without Local ones so I must have scope specified somewhere in the code either in the form of those lines or something else (even more hardcoded).

**Comment by skanct** [comment]
@vrdel, can this be part of a configuration? GOCDB is used also by other projects, so this settings will not be correct for them. So for example you can have a configuration setting "scope", in which we can defined which scope(s) we want to retrieve from the GOCDB

**Comment by vrdel** [comment]
Let me put it this way: is every job that customer defines always tied to a certain scope? There could not be a job defined without scope specified?

**Comment by skanct** [comment]
From what you have said, I understand that the scope is mandatory. If you do not define the scope, you get nothing. If this is the case, we should not hardcode a default value, but we should as a mandatory configuration parameter for the topology connector

**Comment by vrdel** [comment]
No, currently scope is not mandatory. If scope is not specified for a certain job (not listed in any TopoSelect* filtering options), you will get the whole topology EGI + Local. I just thought that we will have jobs that will require whole topology (both scopes) and if that's the case, I believe I need to have somewhere in the code listed all scopes that GOCDB supports because otherwise I couldn't grab the whole topology.

That was my assumption. Later on, I contrived that hey, if there will be a need of whole topology for some job, I could fetch it first, then filter it further if any listed job requires that.

**Comment by eimamagi** [comment]
We discussed it internally. Best is to provide an option to define list of scope tags that the connector will fetch. If nothing is defined, it will fetch whatever GOCDB provides (currently API provides only EGI scoped, but that could be changed by them later).

**Comment by vrdel** [comment]
I fixed this but I didn't introduce new job attribute since Scope is part of topology filtering by tags value that can already be specified in ```TopoSelect*``` options. Basically I wanted that those ```TopoSelect*``` options reflect the filtering by tags and since we agreed that Scope is part of tags, I didn't want to introduce another redundant attribute.

What I did is that, prior any fetching of data from GOCDB, ```topology-gocdb-connector.py``` firstly finds out all Scope tags from  ```customer.conf``` and then it fetchs topology once for each Scope. By that, it's ensured that whole topology that customer will need is fetched once and that there are no hardcoded scopes since I grab them dynamically now from config.

Is that ok?
