### ISSUE TITLE
Hardcoded tenant value in topology connector

### ISSUE THREAD

**Issue by pkoro** [ARGOeu/ARGO#173]
There is a hardcoded reference to EGI tenant [here][l1] in the topology connector. Probably it's best to have this value (name of group) be initialized via the tenant's name in the `customer.conf` configuration. 

@vrdel what do you think?

[l1]: https://github.com/ARGOeu/argo-egi-connectors/blob/devel/bin/topology-gocdb-connector.py#L102

**Comment by vrdel** [comment]
Yes, ok, but how do you want to define it? Now, there's something like this:
```
[CUSTOMER_EGI]
OutputDir = /var/lib/argo-connectors/EGI/
...
```
Do you want some special attribute inside it like:
```
Name = EGI
```
Or should I grab it from section definition so ```[CUSTOMER_EGI]``` means that everything after underscore is customer's name? 

I think the first one is more polite and that we should go with it mainly because I'm not treating specially everything after underscore in job's section definitions either.

**Comment by pkoro** [comment]
Yes, I think the first approach (having the Name explicitly defined in the customer section) is nicer.
