### ISSUE TITLE
Standalone version

### ISSUE THREAD

**Issue by skanct** [ARGOeu/ARGO#98]
- [x] Enable verbose logging for the compute engine when starting up and finally inform user if the CE runs in local or distributed mode (6 @pkoro) @kaggis  
- [x] Make sure that the temporary file created by the CE are properly cleaned up after each local computation (8) @dfolias
- [x] Provide documentation on how to install, configure, run ARGO in Standalone mode (6) @kaggis  
- [x] Test deployment of ARGO Standalone mode (8) @pkoro 
- [x] Test ARGO Standalone mode results (12) @kaggis

**Comment by dfolias** [comment]
Concerning the following sub-issue:
"Make sure that the temporary file created by the CE are properly cleaned up after each local computation"

All directories that are being affected during both local and cluster mode computations runs have been checked. All temporary files are properly cleaned up, but there is a minor issue; In the unlikely event that pig wants to throw a script parameter exception (due to files missing etc) a log file is being created in the execution directory. This small log file contains only stack trace and not valuable syslog information. This file can be written in a user defined path by declaring it as a parameter when calling pig.
